config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/github', as: 'github_login'

  get "/auth/github/callback", to: 'sessions#create'

  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |user|
      user.provider = auth_info["provider"]
      user.uid = auth_info["uid"]
      user.name = auth_info["info"]["name"]
      user.username = auth_info["extra"]["raw_info"]["login"]
      user.token = auth_info["credentials"]["token"]
      user.profile_picture = auth_info["extra"]["raw_info"]["avatar_url"]
      user.bio = auth_info["extra"]["raw_info"]["bio"]
      user.location = auth_info["extra"]["raw_info"]["location"]
      user.email = auth_info["extra"]["raw_info"]["email"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    if user = User.find_by_provider_and_uid(auth["provider"], auth["uid"])
      user.update(token: auth["credentials"]["token"])
    else
      user = User.from_omniauth(auth)
    end
    session[:user_id] = user.id
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @repositories = GithubService.new(current_user).all_repositories
    @followers = GithubService.new(current_user).all_related_users("followers")
    @following = GithubService.new(current_user).all_related_users("following")
    @recent_commits = GithubService.new(current_user).parse_repositories(@repositories).compact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APICurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if current_user %>
      <h1 class="name"><%= current_user.name %></h1>
    <% else %>
      <h1 class="name"><%= link_to "Login", github_login_path %></h1>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div >
    <%= image_tag current_user.profile_picture %>
    <h1><%= current_user.username %></h1>
    <h2><%= current_user.email %></h2>
</div>

<% @repositories.each do |repo| %>
<div class=".trip-card">
  <ul>
    <li><%= repo.name %></li>
    <li><%= repo.full_name %></li>
    <li><%= repo.stargazers_count %></li>
    <li><%= repo.watchers_count %></li>
    <li><%= repo.language %></li>
  </ul>
</div>
<%end %>